function replace(item,msg) {if (item) return item.innerText=chrome.i18n.getMessage(msg); };

replace($("div.title")[0],"extName");
replace($("title")[0],"extName");
replace($("div.subtitle")[0],"subtitle");
replace($("p.intro")[0],"introText");
replace($("p.feat")[0],"featText");
replace($("div.add>label")[0],"addLbl");
replace($("div.delete-all>label")[0],"delAllLbl");
replace($("div.url>label"),"urlLbl");
replace($("div.description>label")[0],"descLbl");
replace($("div.script>label")[0],"scriptLbl");
replace($("div.style>label")[0],"styleLbl");
replace($("div.autorun>label")[0],"autRunLbl");
replace($("div.jquery>label")[0],"jQueryLbl");
replace($("div.regex>label")[0],"RegExLbl");
replace($("div.autostyle>label")[0],"autStyLbl");
replace($("div.inject>label")[0],"injectLbl");
replace($("div.save>label")[0],"saveLbl");
replace($("div.delete>label")[0],"delLbl");
replace($("div.empty-msg")[0],"emptyDb");
replace($("div.unsaved")[0],"unsaved");
replace($("ul.feat_list>li")[0],"featureA");
replace($("ul.feat_list>li")[1],"featureB");
replace($("ul.feat_list>li")[2],"featureC");
replace($("ul.feat_list>li")[3],"featureD");
replace($("ul.feat_list>li")[4],"featureE");